### PR TITLE
Working version with the latest packages

### PR DESCRIPTION
**Pull request by joe9**

### CODE REVIEW

**Comment by JavierJF** [comment]
@joe9 In which system has you tested the MultipleWindows code? In mine isn't working. I'm going to take a look,  but please send details about you system if it's working on it.

**Comment by joe9** [comment]
@JavierJF on further testing, this approach to using multiple windows is not recommended by GLFW. GLFW wants all creation/destruction to be in the main thread. [http://www.glfw.org/docs/latest/intro_guide.html#thread_safety](http://www.glfw.org/docs/latest/intro_guide.html#thread_safety)

**Comment by JavierJF** [comment]
@joe9 Just for clarification, multiple windows are possible in GLFW, the only limitation is as you mark the creation/destruction from the main thread (thing they do because they need to be consistent between all platforms). Since they added "glfwMakeContextCurrent" in version 3.0 you can select the current context on a given thread. Taking that into account it's ease to refactor this to make a "multiple windows" example. I have done it, and all works fine. If you want I could patch this pull request, to add it as an example, remember that is always better to work with real os threads (forkOS) when you are dealing with bindings that need a current thread context in other case, you are not guarantee that all will behave just well.

**Comment by joe9** [comment]
@JavierJF Thanks for taking the program to the logical conclusion. 

I found this comment enlightening: [https://ask.slashdot.org/comments.pl?sid=50400&cid=5100242](https://ask.slashdot.org/comments.pl?sid=50400&cid=5100242)

After reading that, I realized that Xlib is the issue and not glfw/gtk. More saner options are XCB or Wayland.

**Pull request closed without merging**
